### ISSUE TITLE
error in picamera encoders.py

### ISSUE THREAD

**Issue by ymouse91** [davejavu1969/OpenCV_line_follower#1]
After correcting the obvious intend error in KeyboardInterrupt I get the following error message (I get the same error also when using Python3):

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "OpenCV_line_follower.py", line 123, in run
    camera.capture_sequence(self.TriggerStream(), format='bgr', use_video_port=True)
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1518, in capture_sequence
    encoder.start(outputs)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1166, in start
    super(PiRawImageMixin, self).start(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 375, in start
    self._open_output(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1041, in _open_output
    self._next_output(key)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1201, in _next_output
    super(PiRawMultiImageEncoder, self)._next_output(key)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1049, in _next_output
    super(PiMultiImageEncoder, self)._open_output(next(self._output_iter), key)
StopIteration

Program terminated.

**Comment by ymouse91** [comment]
OK. Fixed this by adding a loop to actually capture multiple frames. Place after the line 
_captureThread = ImageCapture ()_
this
_try:
    print('\nCTRL+C to stop')
    while running: #loop until break
        time.sleep(1.0)
except KeyboardInterrupt:
    print('\nUser shutdown')_

Give value for variable **running** in the beginning of the program (i.e _running = True_)
Also global variable **debug** needs a value (e.g. True). The variable **colour** is obsolate and need to be removed from the function  _ProcessImage_
